#!/usr/bin/env node
/**
 * Copy the payload into a consuming repository.
 *
 * WHAT THIS REPLACED, AND WHY. This sync was described in 1,325 lines of
 * `sync-manifest.yml` and validated by 1,176 lines of `check-manifest.mjs`,
 * and it had never been written. Measured against the manifest before it was
 * deleted: of the 20 routes it declared, 18 were exactly `core/X -> X`, and
 * the 2 exceptions were both `*.template.*` files landing under their real
 * name. Every `exclude:` in it existed only because one tree had been split
 * into thirteen groups; each excluded file was carried by another group, so
 * the net effect was that every file under `core/` shipped.
 *
 * So the manifest encoded two rules, and this file is those two rules.
 *
 * THE STAGING APPARATUS IS GONE ON PURPOSE. `status: staged|ready`, the
 * `requires` graph, cohorts and `flipsWith` existed to sequence a rollout to
 * live consumers. Nothing is launched and no consumer depends on this payload,
 * so there is no rollout risk to sequence -- the machinery was managing a
 * hazard that does not yet exist. When a consumer is live and a staged
 * rollout is genuinely needed, the thing to add is the smallest mechanism
 * that delivers it, not this one back.
 *
 * Usage:
 *   node scripts/sync.mjs --to <consumer-repo-path> [--dry-run]
 */
import {
  readdirSync,
  statSync,
  mkdirSync,
  copyFileSync,
  existsSync,
  realpathSync,
  readFileSync,
  writeFileSync,
  rmSync,
} from "node:fs";
import { join, dirname, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PAYLOAD = join(REPO_ROOT, "core");

/**
 * What the last sync delivered, recorded in the consumer.
 *
 * WHY THIS EXISTS. Copying only ever adds. A payload file that is deleted or
 * renamed here stays in every consumer forever, still loaded, still obeyed --
 * a second source of truth, which is the exact failure this repository exists
 * to remove. Nothing about "copy core/** across" notices a removal, and a
 * sync that silently leaves stale contracts behind reports success while
 * doing the wrong thing.
 *
 * It is a RECORD OF WHAT HAPPENED, not a routing table. That distinction is
 * the whole reason it is safe to add here: it is generated by the sync,
 * never hand-edited, and describes the past rather than declaring the future.
 * The deleted manifest was the opposite of all three.
 *
 * Only paths listed here are ever removed, so a consumer's own files are
 * untouchable no matter where they sit.
 */
const LEDGER = ".agents/synced-files.json";

/** Every file under `core/`, as paths relative to it. */
export function payloadFiles(dir = PAYLOAD, base = PAYLOAD) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...payloadFiles(full, base));
    else out.push(relative(base, full));
  }
  return out.sort();
}

/**
 * Where one payload file lands, and whether it is a seed.
 *
 * A SEED is copied under its real name and ONLY when absent.
 * `settings.json` and `machinery.json` are consumer-owned from the moment
 * they land -- a consumer edits its own permissions and its own repo
 * identity. Overwriting them on every sync would clobber that, which is the
 * one way this script could destroy work rather than merely deliver it.
 *
 * Exported and pure so the rule can be tested directly, rather than by
 * copying files and looking at a directory afterwards.
 */
export function routeOf(rel) {
  const parts = rel.split("/");
  const name = parts[parts.length - 1];
  // `.template` sits immediately before the final extension
  // (`machinery.template.json`), NOT at the end of the stem -- reading it as
  // a stem suffix matched nothing and silently shipped the template under its
  // own name. Caught by the equivalence oracle against the old manifest.
  const seeded = name.replace(/\.template(?=\.[^.]+$)/, "");
  if (seeded !== name) return { to: [...parts.slice(0, -1), seeded].join("/"), seed: true };
  return { to: rel, seed: false };
}

/** What the previous sync into `dest` delivered, or [] if it never ran. */
export function previouslyDelivered(dest) {
  try {
    const parsed = JSON.parse(readFileSync(join(dest, LEDGER), "utf8"));
    return Array.isArray(parsed?.files) ? parsed.files.filter((f) => typeof f === "string") : [];
  } catch {
    // Absent, unreadable or malformed all mean the same thing: nothing can be
    // proven about what was delivered, so nothing is removed. Failing toward
    // "delete nothing" is the only safe direction here.
    return [];
  }
}

export function sync(dest, { dryRun = false, log = console.log } = {}) {
  const counts = { copied: 0, seeded: 0, seedKept: 0, removed: 0 };
  const delivered = [];

  for (const rel of payloadFiles()) {
    const { to, seed } = routeOf(rel);
    const target = join(dest, to);
    if (seed && existsSync(target)) {
      counts.seedKept += 1;
      log(`  keep   ${to}  (seed, already present -- consumer owns it)`);
      continue;
    }
    if (!dryRun) {
      mkdirSync(dirname(target), { recursive: true });
      copyFileSync(join(PAYLOAD, rel), target);
    }
    // A seed is recorded only when this sync actually wrote it. One the
    // consumer already owned is deliberately left out of the ledger: it is
    // their file, and a later sync must never be able to delete it.
    if (!seed) delivered.push(to);
    if (seed) {
      counts.seeded += 1;
      log(`  seed   ${rel}  ->  ${to}`);
    } else {
      counts.copied += 1;
      log(`  copy   ${to}`);
    }
  }

  // Anything the last sync delivered that this one did not: the file left the
  // payload, so remove the copy rather than leaving a contract nobody here
  // still ships.
  const current = new Set(delivered);
  for (const stale of previouslyDelivered(dest)) {
    if (current.has(stale)) continue;
    const target = join(dest, stale);
    if (!existsSync(target)) continue;
    if (!dryRun) rmSync(target, { force: true });
    counts.removed += 1;
    log(`  remove ${stale}  (left the payload)`);
  }

  if (!dryRun) {
    mkdirSync(dirname(join(dest, LEDGER)), { recursive: true });
    writeFileSync(
      join(dest, LEDGER),
      `${JSON.stringify({ syncedAt: new Date().toISOString(), files: delivered.sort() }, null, 2)}\n`,
    );
  }
  return counts;
}

function main(argv) {
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--to") flags.to = argv[++i];
    else if (argv[i] === "--dry-run") flags.dryRun = true;
    else throw new Error(`unknown argument ${argv[i]}`);
  }
  if (!flags.to) throw new Error("usage: node scripts/sync.mjs --to <consumer-repo-path> [--dry-run]");
  const dest = resolve(flags.to);
  if (!existsSync(dest)) throw new Error(`destination ${dest} does not exist`);
  // Compare CANONICAL paths. `resolve` normalises `..` and makes a path
  // absolute but does not follow symlinks, so a symlinked checkout reaches
  // this repo under a different string, the equality fails, and the sync
  // then writes core/ over the handbook's own root -- the one destination
  // this refusal exists to prevent, arriving through the alias.
  if (realpathSync(dest) === realpathSync(REPO_ROOT)) {
    throw new Error("refusing to sync the handbook onto itself");
  }

  console.log(`sync: ${PAYLOAD} -> ${dest}${flags.dryRun ? "  (dry run)" : ""}`);
  const c = sync(dest, { dryRun: flags.dryRun });
  console.log(
    `sync: ${c.copied} file(s) copied, ${c.seeded} seeded, ${c.seedKept} seed(s) left alone` +
      `${flags.dryRun ? " -- nothing written" : ""}`,
  );
}

// Compare as a URL: a checkout path needing escaping (a space, a `#`) makes a
// hand-built `file://` string differ from `import.meta.url`, and this would
// then silently do nothing. Same defect as #11, same fix.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main(process.argv.slice(2));
  } catch (e) {
    console.error(`sync: ${e.message}`);
    process.exit(1);
  }
}
